###
# Copyright (c) 2012, Roland Hieber
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions, and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions, and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#   * Neither the name of the author of this software nor the name of
#     contributors to this software may be used to endorse or promote products
#     derived from this software without specific prior written consent.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

###

import os
from datetime import datetime
import supybot.utils as utils
from supybot.commands import *
import supybot.plugins as plugins
import supybot.ircutils as ircutils
import supybot.callbacks as callbacks


class StratumMonitor(callbacks.Plugin):
  """Add the help for "@plugin help StratumMonitor" here
  This should describe *how* to use this plugin."""
  pass

  def __init__(self, irc):
    self.__parent = super(StratumMonitor, self)
    self.__parent.__init__(irc)
    self.htaccess = "/var/www/stuff/stratum0/status/.htaccess"
    self.weekdays = ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"]
  
  def time(self):
    date = datetime.now()
    return "%s, %s" % (self.weekdays[date.weekday()], date.strftime("%H:%M"))
  
  # prints nick of caller and time
  def spaceopen(self, irc, msg, args):
    """
    This command is for internal use only. Any unauthorized use will be
    prohibited. If you use it anyhow, this command will eat your dog, fry it
    and quarter it (in exactly this order). If you have no dog, it will do the
    same with your Nyan cat instead."
    """
    f = open(self.htaccess, "w")
    f.write('''# This file is generated by the Open/Close Monitor.
      RewriteEngine on
      RewriteBase /stuff/stratum0/status
      RewriteRule ^status\.png$ open.png [R,L]
      ''')
    f.flush()
    f.close()
    irc.reply("Space ist offen (Stand: %s)" % self.time(),
      prefixNick=False)
  
  spaceopen = wrap(spaceopen)
  
  def spaceclosed(self, irc, msg, args):
    """
    This command is for internal use only. Any unauthorized use will be
    prohibited. If you use it anyhow, this command will eat your dog, fry it
    and quarter it (in exactly this order). If you have no dog, it will do the
    same with your Nyan cat instead."
    """
    f = open(self.htaccess, "w")
    f.write('''# This file is generated by the Open/Close Monitor.
      RewriteEngine on
      RewriteBase /stuff/stratum0/status
      RewriteRule ^status\.png$ closed.png [R,L]
      ''')
    f.flush()
    f.close()
    irc.reply("Space ist zu (Stand: %s)" % self.time(),
      prefixNick=False)

  spaceclosed = wrap(spaceclosed)
  
Class = StratumMonitor

# vim:set shiftwidth=4 softtabstop=4 expandtab textwidth=79:
